name: appindicators-parts
version: 0.5
confinement: strict
description: |
  Parts to show app-indicators for gtk2, gtk3, qt4 and qt5.
  .
  Usage:
    1. add "after: [indicator-<technology>]" to your part:
       - gtk2, gtk3, qt4 and qt5 corresponds to their respective toolkit.
         main dependencies and default choices.
    2. add 'unity7' plug to your application

parts:
  indicator-qt4:
    plugin: nil
    stage-packages:
      - sni-qt

  indicator-qt5:
    plugin: nil
    stage-packages:
      - appmenu-qt5

  indicator-gtk2:
    plugin: nil
    stage-packages:
      - libappindicator1

  indicator-gtk3:
    plugin: nil
    stage-packages:
      - libappindicator3-1

  # Legacy parts that are built from sources

  indicator-qt4-from-src:
    source: lp:sni-qt
    plugin: cmake
    build-packages:
      - libdbusmenu-qt-dev
      - libqt4-dev
      - pkg-config
      - qt4-qmake


  indicator-qt5-from-src:
    source: lp:appmenu-qt5
    plugin: qmake
    qt-version: qt5
    build-packages:
      - libdbusmenu-qt5-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgles2-mesa-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libinput-dev
      - libmtdev-dev
      - libqt5x11extras5-dev
      - libudev-dev
      - libxrender-dev
      - pkg-config
      - qtbase5-dev
      - qtbase5-private-dev


  indicator-gtk2-from-src:
    plugin: autotools
    source: lp:libappindicator
    build-packages:
      - at-spi2-core
      - gnome-common
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - libdbus-glib-1-dev
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libindicator-dev
      - python-all-dev
      - python-gtk2-dev
      - valac

      # #Mono support
      # - cli-common-dev # [!arm64 !ppc64el]
      # - libnunit-cil-dev # [!arm64 !ppc64el]
      # - mono-devel # [!arm64 !ppc64el]
      # - gtk-sharp2-gapi # [!arm64 !ppc64el]
      # - libgtk2.0-cil-dev # [!arm64 !ppc64el]

    configflags:
      - --prefix=/usr
      - --with-gtk=2
      - --enable-gtk-doc=no
      - --enable-gtk-doc-html=no
      - --disable-tests
      - --disable-mono-test

    prime:
      - ./**/lib*.so.*
      - ./**/*.typelib
      - ./**/python2.7/**/appindicator
      - ./**/lib/cli
      - ./**/lib/mono


  indicator-gtk3-from-src:
    source: lp:libappindicator
    plugin: autotools
    build-packages:
      - at-spi2-core
      - gnome-common
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - libdbus-glib-1-dev
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk3-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libindicator3-dev
      - python-all-dev
      - python-gtk2-dev
      - valac

      # #Mono support
      # - cli-common-dev # [!arm64 !ppc64el]
      # - libnunit-cil-dev # [!arm64 !ppc64el]
      # - mono-devel # [!arm64 !ppc64el]
      # - gtk-sharp2-gapi # [!arm64 !ppc64el]
      # - libgtk2.0-cil-dev # [!arm64 !ppc64el]

    configflags:
      - --prefix=/usr
      - --with-gtk=3
      - --enable-gtk-doc=no
      - --enable-gtk-doc-html=no
      - --disable-tests
      - --disable-mono-test

    prime:
      - ./**/lib*.so.*
      - ./**/*.typelib
      - ./**/lib/cli
      - ./**/lib/mono
